# permissions for end users to edit homepageentries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: homepage-operator
    app.kubernetes.io/managed-by: kustomize
  name: homepageentry-editor-role
rules:
- apiGroups:
  - homepage.nathanyu.com
  resources:
  - homepageentries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - homepage.nathanyu.com
  resources:
  - homepageentries/status
  verbs:
  - get
